version: "3.7"
services:

  redis-cluster:
    image: ${REDIS_IMAGE}
    container_name: init-redis-cluster
    command: redis-cli --cluster create 172.28.0.101:6377 172.28.0.102:6378 172.28.0.103:6379 172.28.0.104:6380 172.28.0.105:6381 172.28.0.106:6382 --cluster-replicas 1 --cluster-yes
    environment:
      - REDISCLI_AUTH=test1234
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.107
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  redis-node-1:
    image: ${REDIS_IMAGE}
    container_name: redis-node1
    command: [ "redis-server", "/conf/redis.conf", "--port 6377" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6377:6377
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.101

  redis-node-2:
    image: ${REDIS_IMAGE}
    container_name: redis-node2
    command: [ "redis-server", "/conf/redis.conf", "--port 6378" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6378:6378
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.102

  redis-node-3:
    image: ${REDIS_IMAGE}
    container_name: redis-node3
    command: [ "redis-server", "/conf/redis.conf", "--port 6379" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.103

  redis-node-4:
    image: ${REDIS_IMAGE}
    container_name: redis-node4
    command: [ "redis-server", "/conf/redis.conf", "--port 6380" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6380:6380
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.104

  redis-node-5:
    image: ${REDIS_IMAGE}
    container_name: redis-node5
    command: [ "redis-server", "/conf/redis.conf", "--port 6381" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6381:6381
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.105

  redis-node-6:
    image: ${REDIS_IMAGE}
    container_name: redis-node6
    command: [ "redis-server", "/conf/redis.conf", "--port 6382" ]
    environment:
      - REDISCLI_AUTH=test1234
    ports:
      - 6382:6382
    volumes:
      - ./redis.conf:/conf/redis.conf
    networks:
      aries-load-test:
        ipv4_address: 172.28.0.106

networks:
  aries-load-test:
    external: true
    name: aries-load-test
