spring:
    datasource:
        url: jdbc:postgresql://issuer-verifier-wallet-db:5432/

logging:
    config: classpath:logback-spring-docker.xml

issuer-verifier:
    acapy:
        url: 'http://issuer-verifier-nginx:10000'

holder:
    acapy:
        urls: 'http://holder-acapy-1:10010, http://holder-acapy-2:10010'
