spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # required for the Swagger UI to work

issuer-verifier:
  acapy:
    api-key:
    url: "http://localhost:10000"

holder:
  acapy:
    api-key:
    url: "http://localhost:10010"

test-cases:
  full-process:
    active: true
    number-of-iterations: 10
    number-of-parallel-iterations: 2

