spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: postgres
        password: postgres
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher # required for the Swagger UI to work

logging:
    config: classpath:logback-spring.xml

issuer-verifier:
    acapy:
        api-key:
        url: 'http://localhost:10000'
        http-timeout: 60
    wallet-db-name: wallet_db

holder:
    acapy:
        api-key:
        url: 'http://localhost:10010'
        http-timeout: 60

test-cases:
    full-process-max-parallel-iterations:
        active: false
        number-of-iterations: 100
        number-of-parallel-iterations: 5
    full-process-constant-load:
        active: true
        number-of-iterations: 100
        number-of-iterations-per-minute: 30
