spring:
    datasource:
        url: jdbc:postgresql://issuer-verifier-wallet-db:5000/

logging:
    config: classpath:logback-spring-docker.xml

issuer-verifier:
    acapy:
        url: 'http://issuer-verifier-nginx:10000'

holder:
    acapy:
        urls: 'http://agents_holder-acapy_1:10010'
