version: "3.7"
services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - acapy-load-test
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-volume:/data/loki
    depends_on:
      - grafana
    networks:
      - acapy-load-test
  issuer-verifier-wallet-db:
    container_name: issuer-verifier-wallet-db
    image: ${POSTGRES_IMAGE}
    volumes:
      - issuer-verifier-wallet-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - acapy-load-test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    ports:
      - 5432:5432
    restart: always

  issuer-verifier-acapy:
    container_name: issuer-verifier-acapy
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
      "-c",
      "sleep 10;
        aca-py start \
        --auto-provision
        --inbound-transport http 0.0.0.0 10001 \
        --outbound-transport http \
        --admin 0.0.0.0 10000 \
        --endpoint http://issuer-verifier-acapy:10001 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --invite-base-url didcomm://aries_connection_invitation \
        --admin-insecure-mode \
        --label issuer_verifier_acapy \
        --wallet-type indy \
        --wallet-name ${POSTGRES_DB} \
        --wallet-key key \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{\"url\":\"issuer-verifier-wallet-db:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRES_USER}\",\"password\":\"${POSTGRES_PASSWORD}\",\"admin_account\":\"${POSTGRES_USER}\",\"admin_password\":\"${POSTGRES_PASSWORD}\"}' \
        --auto-ping-connection \
        --auto-verify-presentation \
        --invite-public \
        --public-invites \
        --invite-multi-use \
        --tails-server-base-url ${ACAPY_TAILS_SERVER_BASE_URL} \
        --seed ${ISSUER_DID_SEED} \
        --log-level ${ACAPY_LOG_LEVEL} \
        --webhook-url ${LOAD_GENERATOR_WEBHOOK_ENDPOINT} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    ports:
      - "127.0.0.1:10000:10000" # AcaPy Admin API
    depends_on:
      - issuer-verifier-wallet-db
      - tails-server
    networks:
      - acapy-load-test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: always

  holder-wallet-db:
    container_name: holder-wallet-db
    image: ${POSTGRES_IMAGE}
    volumes:
      - holder-wallet-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - acapy-load-test
    restart: always

  holder-acapy:
    container_name: holder-acapy
    image: ${ACAPY_IMAGE}
    entrypoint: /bin/bash
    command: [
      "-c",
      "sleep 10;
        aca-py start \
        --auto-provision \
        --inbound-transport http 0.0.0.0 10011 \
        --outbound-transport http \
        --admin 0.0.0.0 10010 \
        --endpoint http://holder-acapy:10011 \
        --genesis-url ${LEDGER_GENESIS} \
        --ledger-pool-name $LEDGER_POOL_NAME \
        --ledger-pool-name ${LEDGER_POOL_NAME} \
        --admin-insecure-mode \
        --label holder_acapy \
        --wallet-type indy \
        --wallet-name ${POSTGRES_DB} \
        --wallet-key key \
        --wallet-storage-type postgres_storage \
        --wallet-storage-config '{\"url\":\"holder-wallet-db:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRES_USER}\",\"password\":\"${POSTGRES_PASSWORD}\",\"admin_account\":\"${POSTGRES_USER}\",\"admin_password\":\"${POSTGRES_PASSWORD}\"}' \
        --auto-accept-invites \
        --invite-public \
        --public-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-credential-offer \
        --auto-respond-credential-proposal \
        --auto-respond-credential-request \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-respond-presentation-request \
        --auto-respond-presentation-proposal \
        --auto-verify-presentation \
        --log-level ${ACAPY_LOG_LEVEL} \
        ${ACAPY_DEBUG_OPTIONS}"
    ]
    ports:
      - "127.0.0.1:10010:10010" # AcaPy Admin API
    depends_on:
      - holder-wallet-db
      - tails-server
    networks:
      - acapy-load-test
    restart: always
  
  tails-server:
    container_name: tails-server
    build:
      context: ./indy-tails-server
      dockerfile: docker/Dockerfile.tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

    volumes:
      - tails-server-volume:/home/indy/tails-files
    ports:
      - 6543:6543
    networks:
      - acapy-load-test
    restart: always


networks:
  acapy-load-test:
    name: acapy-load-test

volumes:
  grafana-volume:
  loki-volume:
  issuer-verifier-wallet-db-volume:
  holder-wallet-db-volume:
  tails-server-volume:
