version: "3.7"
services:

  load-generator:
    container_name: load-generator
    build: ../
    # TODO I think env_file could work here
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - HOLDER_ACAPY_URLS=${HOLDER_ACAPY_URLS}
      - TESTRUNNERS_MAXPARALLELITERATIONSRUNNER_ACTIVE=${TEST_RUNNERS_MAX_PARALLEL_ITERATIONS_RUNNER_ACTIVE}
      - TESTRUNNERS_MAXPARALLELITERATIONSRUNNER_NUMBEROFTOTALITERATIONS=${TEST_RUNNERS_MAX_PARALLEL_ITERATIONS_RUNNER_NUMBER_OF_TOTAL_ITERATIONS}
      - TESTRUNNERS_MAXPARALLELITERATIONSRUNNER_NUMBEROFPARALLELITERATIONS=${TEST_RUNNERS_MAX_PARALLEL_ITERATIONS_RUNNER_NUMBER_OF_PARALLEL_ITERATIONS}
      - TESTRUNNERS_CONSTANTLOADRUNNER_ACTIVE=${TEST_RUNNERS_CONSTANT_LOAD_RUNNER_ACTIVE}
      - TESTRUNNERS_CONSTANTLOADRUNNER_NUMBEROFTOTALITERATIONS=${TEST_RUNNERS_CONSTANT_LOAD_RUNNER_NUMBER_OF_TOTAL_ITERATIONS}
      - TESTRUNNERS_CONSTANTLOADRUNNER_NUMBEROFITERATIONSPERMINUTE=${TEST_RUNNERS_CONSTANT_LOAD_RUNNER_NUMBER_OF_ITERATIONS_PER_MINUTE}
      - TESTRUNNERS_CONSTANTLOADRUNNER_THREADPOOLSIZE=${TEST_RUNNERS_CONSTANT_LOAD_RUNNER_THREAD_POOL_SIZE}
      - TESTRUNNERS_INCREASINGLOADRUNNER_ACTIVE=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_ACTIVE}
      - TESTRUNNERS_INCREASINGLOADRUNNER_PEAKDURATIONINMINUTES=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_PEAK_DURATION_IN_MINUTES}
      - TESTRUNNERS_INCREASINGLOADRUNNER_SLEEPBETWEENPEAKSINMINUTES=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_SLEEP_BETWEEN_PEAKS_IN_MINUTES}
      - TESTRUNNERS_INCREASINGLOADRUNNER_INITIALNUMBEROFITERATIONSPERMINUTE=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_INITIAL_NUMBER_OF_ITERATIONS_PER_MINUTE}
      - TESTRUNNERS_INCREASINGLOADRUNNER_FINALNUMBEROFITERATIONSPERMINUTE=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_FINAL_NUMBER_OF_ITERATIONS_PER_MINUTE}
      - TESTRUNNERS_INCREASINGLOADRUNNER_STEPSIZEOFITERATIONSPERMINUTE=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_STEP_SIZE_OF_ITERATIONS_PER_MINUTE}
      - TESTRUNNERS_INCREASINGLOADRUNNER_THREADPOOLSIZE=${TEST_RUNNERS_INCREASING_LOAD_RUNNER_THREAD_POOL_SIZE}
      - TESTFLOWS_EMPTYFLOW_ACTIVE=${TEST_FLOWS_EMPTY_FLOW_ACTIVE}
      - TESTFLOWS_FULLFLOW_ACTIVE=${TEST_FLOWS_FULL_FLOW_ACTIVE}
      - TESTFLOWS_FULLFLOW_USEREVOCABLECREDENTIALS=${TEST_FLOWS_FULL_FLOW_USE_REVOCABLE_CREDENTIALS}
      - TESTFLOWS_FULLFLOW_REVOCATIONREGISTRYSIZE=${TEST_FLOWS_FULL_FLOW_REVOCATION_REGISTRY_SIZE}
      - TESTFLOWS_FULLFLOW_CHECKNONREVOKED=${TEST_FLOWS_FULL_FLOW_CHECK_NON_REVOKED}
      - TESTFLOWS_FULLFLOW_USEOOBINSTEADOFCONNECTION=${TEST_FLOWS_FULL_FLOW_USE_OOB_INSTEAD_OF_CONNECTION}
      - TESTFLOWS_ISSUERFLOW_ACTIVE=${TEST_FLOWS_ISSUER_FLOW_ACTIVE}
      - TESTFLOWS_ISSUERFLOW_USEREVOCABLECREDENTIALS=${TEST_FLOWS_ISSUER_FLOW_USE_REVOCABLE_CREDENTIALS}
      - TESTFLOWS_ISSUERFLOW_REVOCATIONREGISTRYSIZE=${TEST_FLOWS_ISSUER_FLOW_REVOCATION_REGISTRY_SIZE}
      - TESTFLOWS_ISSUERFLOW_USEOOBCREDENTIALISSUANCE=${TEST_FLOWS_ISSUER_FLOW_USE_OOB_CREDENTIAL_ISSUANCE}
      - TESTFLOWS_CONNECTIONFLOW_ACTIVE=${TEST_FLOWS_CONNECTION_FLOW_ACTIVE}
      - TESTFLOWS_CREDENTIALISSUANCEFLOW_ACTIVE=${TEST_FLOWS_CREDENTIAL_ISSUANCE_FLOW_ACTIVE}
      - TESTFLOWS_CREDENTIALISSUANCEFLOW_USEREVOCABLECREDENTIALS=${TEST_FLOWS_CREDENTIAL_ISSUANCE_FLOW_USE_REVOCABLE_CREDENTIALS}
      - TESTFLOWS_CREDENTIALISSUANCEFLOW_REVOCATIONREGISTRYSIZE=${TEST_FLOWS_CREDENTIAL_ISSUANCE_FLOW_REVOCATION_REGISTRY_SIZE}
      - TESTFLOWS_CREDENTIALISSUANCEFLOW_USEOOBCREDENTIALISSUANCE=${TEST_FLOWS_CREDENTIAL_ISSUANCE_FLOW_USE_OOB_CREDENTIAL_ISSUANCE}
      - TESTFLOWS_PROOFREQUESTFLOW_ACTIVE=${TEST_FLOWS_PROOF_REQUEST_FLOW_ACTIVE}
      - TESTFLOWS_PROOFREQUESTFLOW_REVOCATIONREGISTRYSIZE=${TEST_FLOWS_PROOF_REQUEST_FLOW_REVOCATION_REGISTRY_SIZE}
      - TESTFLOWS_PROOFREQUESTFLOW_CHECKNONREVOKED=${TEST_FLOWS_PROOF_REQUEST_FLOW_CHECK_NON_REVOKED}
      - TESTFLOWS_PROOFREQUESTFLOW_USEOOBPROOFREQUESTS=${TEST_FLOWS_PROOF_REQUEST_FLOW_USE_OOB_PROOF_REQUESTS}
    ports:
      - 8080:8080
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"

networks:
  aries-load-test:
    external: true
    name: aries-load-test
